sonar.projectKey=macod-spec_netflix-devsecops-platform
sonar.organization=macod-spec
sonar.projectName=netflix-devsecops-platform

sonar.sources=apps/web/src,services/api
sonar.tests=
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.terraform/**,**/coverage/**,docs/**,charts/**,argocd/**,environment/**,Modules/**

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true