{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.api.name }}
  {{- if .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.api.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
