name: Terraform Dev Validation

on:
  push:
    branches:
      - main
    paths:
      - "environment/dev/**"
      - "Modules/**"
      - ".github/workflows/terraform-dev.yml"
  pull_request:
    branches:
      - main
    paths:
      - "environment/dev/**"
      - "Modules/**"
      - ".github/workflows/terraform-dev.yml"
  workflow_dispatch:

env:
  TF_WORKING_DIR: environment/dev

jobs:
  terraform-validate:
    name: Terraform Format, Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
                - name: Show Azure login identity
        run: |
          az account show --query "{subscription:id, tenant:tenantId, loggedInAs:user.name, type:user.type}" -o table

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform format check
        run: terraform fmt -check -recursive ../..

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan